### ISSUE TITLE
Quiet mode doesn't remove stack trace on warning level

### ISSUE THREAD

**Issue by Pauleing** [didfet/logstash-forwarder-java#13]
Hey,

When trying to quiet a recurrent warning only the message gets removed and the stack trace persists. 

In my case it happens while logstash-forwarder-java keeps on trying to read an empty file which causes a recurrent warning. It becomes a problem with a lot of empty files and can cause a FS full.

Also wanted to thank you a lot for your program !
Have a good one,
Paul

Log output in normal mode :

2015-06-26 11:00:36,536 WARN FileReader - Exception raised while reading file : /home/jqm/jqm/logs/0000411411.stdout.log
java.io.IOException: Seek failed
        at info.fetter.logstashforwarder.FileReader.isCompressedFile(FileReader.java:87)
        at info.fetter.logstashforwarder.FileReader.readFile(FileReader.java:73)
        at info.fetter.logstashforwarder.FileReader.readFiles(FileReader.java:53)
        at info.fetter.logstashforwarder.FileWatcher.readFiles(FileWatcher.java:103)
        at info.fetter.logstashforwarder.Forwarder.infiniteLoop(Forwarder.java:93)
        at info.fetter.logstashforwarder.Forwarder.main(Forwarder.java:82) 

 Log output in quiet mode :

java.io.IOException: Seek failed
        at info.fetter.logstashforwarder.FileReader.isCompressedFile(FileReader.java:87)
        at info.fetter.logstashforwarder.FileReader.readFile(FileReader.java:73)
        at info.fetter.logstashforwarder.FileReader.readFiles(FileReader.java:53)
        at info.fetter.logstashforwarder.FileWatcher.readFiles(FileWatcher.java:103)
        at info.fetter.logstashforwarder.Forwarder.infiniteLoop(Forwarder.java:93)
        at info.fetter.logstashforwarder.Forwarder.main(Forwarder.java:82)

**Comment by didfet** [comment]
Thanks for this bug report. To prevent the FS full problem you should use the latest version with the logfile option and redirect stdout and stderr to /dev/null. This way log files are rotated and you can control how much space they use. Concerning the stacktrace and empty files I'll investigate ASAP.

**Comment by Pauleing** [comment]
Thought about redirecting to /dev/null but I can't afford it since I need to the logs in case of incident. 
Thanks for helping !

**Comment by didfet** [comment]
I've tried to reproduce the problem with the latest version but everything works even with empty files. Looking at the stacktrace you're using an old version < 0.2.1 where no tests are done before trying to read the file. So maybe just running the latest version will be enough for you.

I'll still make some modifications :
- log the stacktrace with log4j
- test if file size > 0 before reading

**Comment by Pauleing** [comment]
Thank you for the fix !
Problem still occurs for me with version 0.2.2 on an AIX server using Java 5, just so you know.
