### ISSUE TITLE
null pointer error

### ISSUE THREAD

**Issue by gnuhpc** [didfet/logstash-forwarder-java#14]
Firstly, I believe this tool would help me a lot, because I have aix os...

But When I came to use it to collect my log, an null pointer exception  occured. Can anyone helps out?

First： AIX version
6100-04-06-1034

Second：Java Version
java version "1.6.0"
Java(TM) SE Runtime Environment (build pap6460sr14-20130705_01(SR14))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 AIX ppc64-64 jvmap6460sr14-20130704_155156 (JIT enabled, AOT enabled)
J9VM - 20130704_155156
JIT  - r9_20130517_38390
GC   - GA24_Java6_SR14_20130704_1138_B155156)
JCL  - 20130618_01

Config file：

SADB01:/home/cmbcsa/logstash$ cat logforwarder.conf
{
  "network": {
    "servers": [ "40.32.64.52:5043"],
    "ssl certificate": "/home/cmbcsa/logstash/logstash.pub",
    "ssl key": "/home/cmbcsa/logstash/logstash.key"
  },
  "files": [
    {
      "paths": [ "/home/cmbcsa/logstash/1.txt" ],
      "fields": { "type": "SADB" }
    }
  ]
}

Finally command used：
java -jar     logstash-forwarder-java-0.2.2.jar  -debugwatcher -debug -trace -config logforwarder.conf 

2015-07-21 23:16:25,436 DEBUG FileWatcher - Loading saved states
2015-07-21 23:16:25,661 WARN FileWatcher - Could not load saved states : .logstash-forwarder-java (路径名中的文件或目录不存在。)
2015-07-21 23:16:25,799 INFO FileWatcher - Watching file : /home/cmbcsa/logstash/1.txt
2015-07-21 23:16:25,815 DEBUG FileWatcher - Initializing FileWatcher
2015-07-21 23:16:25,815 DEBUG FileWatcher - File /home/cmbcsa/logstash/1.txt has been truncated or created, not retrieving pointer
2015-07-21 23:16:25,833 INFO Forwarder - Trying to connect to 40.32.64.52:5043
2015-07-21 23:16:26,215 ERROR Forwarder - Failed to connect to server 40.32.64.52:5043 : java.lang.NullPointerException
2015-07-21 23:16:26,216 INFO Forwarder - Trying to connect to 40.32.64.52:5043
2015-07-21 23:16:26,216 ERROR Forwarder - Failed to connect to server 40.32.64.52:5043 : java.lang.NullPointerException
2015-07-21 23:16:26,216 INFO Forwarder - Trying to connect to 40.32.64.52:5043
2015-07-21 23:16:26,216 ERROR Forwarder - Failed to connect to server 40.32.64.52:5043 : java.lang.NullPointerException
2015-07-21 23:16:26,216 INFO Forwarder - Trying to connect to 40.32.64.52:5043
2015-07-21 23:16:26,216 ERROR Forwarder - Failed to connect to server 40.32.64.52:5043 : java.lang.NullPointerException
2015-07-21 23:16:26,216 INFO Forwarder - Trying to connect to 40.32.64.52:5043
2015-07-21 23:16:26,217 ERROR Forwarder - Failed to connect to server 40.32.64.52:5043 : java.lang.NullPointerException
2015-07-21 23:16:26,217 INFO Forwarder - Trying to connect to 40.32.64.52:5043
2015-07-21 23:16:26,217 ERROR Forwarder - Failed to connect to server 40.32.64.52:5043 : java.lang.NullPointerException
2015-07-21 23:16:26,217 INFO Forwarder - Trying to connect to 40.32.64.52:5043
2015-07-21 23:16:26,217 ERROR Forwarder - Failed to connect to server 40.32.64.52:5043 : java.lang.NullPointerException

**Comment by gnuhpc** [comment]
BTW, The server is OK.
SADB01:/home/cmbcsa/logstash$ telnet  40.32.64.52 5043
正在尝试...
连接到 40.32.64.52。
换码字符为 '^]'。

**Comment by didfet** [comment]
Hi,

Please try to build the latest commit and run it. I just modified error logging to have a full stacktrace of your error, otherwise it won't be possible to debug it.

**Comment by gnuhpc** [comment]
```
 2015-07-22 10:35:51,776 WARN FileWatcher - Could not load saved states : .logstash-forwarder-java (·- 
```

¼) 
2015-07-22 10:35:51,908 INFO FileWatcher - Watching file : /home/cmbcsa/logstash/1.txt 
2015-07-22 10:35:51,947 INFO Forwarder - Trying to connect to 40.32.64.52:5043 
2015-07-22 10:35:52,299 ERROR Forwarder - Failed to connect to server 40.32.64.52:5043 : 
java.lang.RuntimeException: java.lang.NullPointerException 
at info.fetter.logstashforwarder.protocol.LumberjackClient.<init>(LumberjackClient.java:94) 
at info.fetter.logstashforwarder.Forwarder.connectToServer(Forwarder.java:127) 
at info.fetter.logstashforwarder.Forwarder.main(Forwarder.java:86) 
Caused by: java.lang.NullPointerException 
at java.io.FileInputStream.<init>(FileInputStream.java:133) 
at java.io.FileInputStream.<init>(FileInputStream.java:96) 
at info.fetter.logstashforwarder.protocol.LumberjackClient.<init>(LumberjackClient.java:71) 
... 2 more 
2015-07-22 10:35:52,303 INFO Forwarder - Trying to connect to 40.32.64.52:5043 
2015-07-22 10:35:52,303 ERROR Forwarder - Failed to connect to server 40.32.64.52:5043 : 
java.lang.RuntimeException: java.lang.NullPointerException 
at info.fetter.logstashforwarder.protocol.LumberjackClient.<init>(LumberjackClient.java:94) 
at info.fetter.logstashforwarder.Forwarder.connectToServer(Forwarder.java:127) 
at info.fetter.logstashforwarder.Forwarder.main(Forwarder.java:86) 
Caused by: java.lang.NullPointerException 
at java.io.FileInputStream.<init>(FileInputStream.java:133) 
at java.io.FileInputStream.<init>(FileInputStream.java:96) 
at info.fetter.logstashforwarder.protocol.LumberjackClient.<init>(LumberjackClient.java:71) 
... 2 more

**Comment by gnuhpc** [comment]
I checked the source code and add ssl ca config, New error occured:

2015-07-22 11:14:29,004 ERROR Forwarder - Failed to connect to server 40.32.64.52:5043 : 
java.io.IOException: Invalid keystore format 
at com.ibm.crypto.provider.JavaKeyStore.engineLoad(Unknown Source) 
at java.security.KeyStore.load(KeyStore.java:414) 
at info.fetter.logstashforwarder.protocol.LumberjackClient.<init>(LumberjackClient.java:71) 
at info.fetter.logstashforwarder.Forwarder.connectToServer(Forwarder.java:127) 
at info.fetter.logstashforwarder.Forwarder.main(Forwarder.java:86)

**Comment by gnuhpc** [comment]
After several checking, I found the page as below:
https://github.com/didfet/logstash-forwarder-java/blob/master/HOWTO-KEYSTORE.md

I missed the keystore thing, thank you and close this issue

**Comment by didfet** [comment]
OK , glad you found out what was wrong with your config. I added a test in LumberjackClient to raise an exception if the keystore path or the server address are not configured.
