### ISSUE TITLE
[0.2.4] Cannot run LSF on AIX -  Could not load saved states 

### ISSUE THREAD

**Issue by pdanysz** [didfet/logstash-forwarder-java#27]
Hi,

I don't know if this repo is still maintained, but I downloaded it, and try to run.
But first:

**OS**:  `AIX 7100-04-03-1642`
**JAVA**: `java version "1.7.0"
Java(TM) SE Runtime Environment (build pap6470sr9fp60-20161021_01(SR9 FP60))
IBM J9 VM (build 2.6, JRE 1.7.0 AIX ppc64-64 Compressed References 20161005_321282 (JIT enabled, AOT enabled)
J9VM - R26_Java726_SR9_20161005_1259_B321282
JIT  - tr.r11_20161001_125404
GC   - R26_Java726_SR9_20161005_1259_B321282_CMPRSS
J9CL - 20161005_321282)`

So jar is starting but, it can't find file called **.logstash-forwarder-java**,

`[myAIX /gitlab/logstash-forwarder-java-0.2.4]# java -jar logstash-forwarder-java-0.2.4.jar -config `pwd`/config.json -debug
2017-03-02 16:11:40,329 DEBUG FileWatcher - Loading saved states
2017-03-02 16:11:40,642 WARN FileWatcher - Could not load saved states : .logstash-forwarder-java (A file or directory in the path name does not exist.)
java.io.FileNotFoundException: .logstash-forwarder-java (A file or directory in the path name does not exist.)
        at java.io.FileInputStream.<init>(FileInputStream.java:158)
        at com.fasterxml.jackson.core.JsonFactory.createJsonParser(JsonFactory.java:768)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1897)
        at info.fetter.logstashforwarder.Registrar.readStateFromJson(Registrar.java:35)
        at info.fetter.logstashforwarder.Registrar.readStateFromJson(Registrar.java:40)
        at info.fetter.logstashforwarder.FileWatcher.setSincedb(FileWatcher.java:375)
        at info.fetter.logstashforwarder.Forwarder.main(Forwarder.java:78)
java.lang.NullPointerException
        at info.fetter.logstashforwarder.Event.<init>(Event.java:37)
        at info.fetter.logstashforwarder.Forwarder.main(Forwarder.java:83)`

So, I created it manualy, add JSON entries ,  {[]}, but next problem occur with parse:
`2017-03-02 16:15:59,946 DEBUG FileWatcher - Loading saved states
2017-03-02 16:16:00,357 WARN FileWatcher - Could not load saved states : Can not deserialize instance of info.fetter.logstashforwarder.FileState[] out of START_OBJECT token
 at [Source: .logstash-forwarder-java; line: 1, column: 1]
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of info.fetter.logstashforwarder.FileState[] out of START_OBJECT token
 at [Source: .logstash-forwarder-java; line: 1, column: 1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
        at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:599)
        at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:593)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.handleNonArray(ObjectArrayDeserializer.java:220)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:131)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:18)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2793)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1897)
        at info.fetter.logstashforwarder.Registrar.readStateFromJson(Registrar.java:35)
        at info.fetter.logstashforwarder.Registrar.readStateFromJson(Registrar.java:40)
        at info.fetter.logstashforwarder.FileWatcher.setSincedb(FileWatcher.java:375)
        at info.fetter.logstashforwarder.Forwarder.main(Forwarder.java:78)
java.lang.NullPointerException
        at info.fetter.logstashforwarder.Event.<init>(Event.java:37)
        at info.fetter.logstashforwarder.Forwarder.main(Forwarder.java:83)`

---
**So how you can help with that?**

**Comment by didfet** [comment]
Hi, this message is a warning, not an error. The first time you run the program, the sincedb file does not exist, which is normal. It is automatically created after the program reads the first lines of your log files.
